// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Job struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	CompanyName string    `json:"companyName"`
	City        string    `json:"city"`
	Country     string    `json:"country"`
	Status      string    `json:"status"`
	Description string    `json:"description"`
	Creator     string    `json:"creator"`
	TimeStamp   time.Time `json:"timeStamp"`
}

type NewJob struct {
	Title       string `json:"title"`
	CompanyName string `json:"companyName"`
	City        string `json:"city"`
	Country     string `json:"country"`
	Status      string `json:"status"`
	Description string `json:"description"`
}

type NewLink struct {
	Link   string `json:"link"`
	UserID string `json:"userID"`
}

type UpdateUser struct {
	Name      string  `json:"name"`
	FirstName string  `json:"firstName"`
	LastName  *string `json:"lastName"`
	Pronoun   *string `json:"pronoun"`
	Headline  *string `json:"headline"`
	Position  *string `json:"position"`
	Region    *string `json:"region"`
}
