// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewLink struct {
	Link   string `json:"link"`
	UserID string `json:"userID"`
}

type NewUpdateUser struct {
	Name              string  `json:"name"`
	Email             string  `json:"email"`
	FirstName         string  `json:"firstName"`
	LastName          *string `json:"lastName"`
	Pronoun           *string `json:"pronoun"`
	Headline          *string `json:"headline"`
	Position          *string `json:"position"`
	Region            *string `json:"region"`
	About             *string `json:"about"`
	ProfilePicture    *string `json:"profilePicture"`
	BackgroundPicture *string `json:"backgroundPicture"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID                string  `json:"id"`
	Name              string  `json:"name"`
	Email             string  `json:"email"`
	Password          string  `json:"password"`
	FirstName         string  `json:"firstName"`
	LastName          *string `json:"lastName"`
	Pronoun           *string `json:"pronoun"`
	Headline          *string `json:"headline"`
	Position          *string `json:"position"`
	Region            *string `json:"region"`
	About             *string `json:"about"`
	ProfilePicture    string  `json:"profilePicture"`
	BackgroundPicture *string `json:"backgroundPicture"`
	IsActive          bool    `json:"isActive"`
}
